### ISSUE TITLE
Testar todos os fluxos de trabalho do sistema, em decorrência do merge v3.3 > v4.0

### ISSUE THREAD

**Issue by moacirmoda** [institutotim/timtec#53]
Testar todos os fluxos de trabalho do sistema e documentar possíveis erros e bugs. Basear-se na lista abaixo:

- Administrador
    - [x] (#54) Gestão de usuários (Tela de gestão de usuários) 
    - [x] (#54) Mudar papéis dos usuários
    - [x] (#54) Bloquear e desbloquear usuário

- Administração Geral
    - [x] (#55) Administração da Página Inicial
    - [x] (#55) Escolher os cursos que terão destaque na home, bem como seu ordem
    - [ ] (NÃO ACHEI) Editar conteúdo do Termo de Uso
    - [x] (OK) Editar conteúdo da página "Sobre"

- Gestão dos cursos
    - [x] (#56) Listar cursos (admin)
    - [x] (#56) Criar cursos
    - [x] (#56) Acesso aos relatórios de gestão (Tela de relatórios de gestão)
    - [x] (#56) Número de usuário que terminaram pelo menos um curso.
    - [x] (#56) Porcentagem de alunos alunos atualizaram o perfil com mais informações depois do primeiro cadastro

- Gestão dos cursos
    - [x] (#56) Publicar (e mudar o status) dos cursos
    - [x] (#56) Definir data de início de um curso
    - [x] (#56) Editar todos os campos da introdução dos cursos e das aulas
    - [x] (#56) Criar Unidades, vídeos e atividades
    - [x] (#56) Acesso aos relatórios de gestão (Tela de relatórios de gestão) do curso para todas as turmas

- Gestão de professores do curso
    - [x] (#56) Adicionar ou remover professor do curso.
    - [x] (#56) Definir papel do professor no curso

- Estatísticas
    - [ ] (NÃO ACHEI) Número total de usuário que concluíram cada curso
    - [ ] (NÃO ACHEI) Porcentagem dos alunos que concluíram cada curso
    - [ ] (NÃO ACHEI) Número de alunos por curso
    - [ ] (NÃO ACHEI) Estatísticas por turma
    - [ ] (NÃO ACHEI) Mesmas estatísticas do professor tutor, porém com a possibilidade de ver dados de todas as turmas.

- Mensagens
    - [x] (#57) Enviar mensagens para todos os alunos do curso, ou para qualquer turma do curso

- Gestão de turmas (Tela de gestão de turmas)
    - [x] (OK) Excluir Turmas
    - [x] (#58) Alterar professor(es) tutor(es) das turmas
    - [x] (#58) Inserir e apagar estudantes das turmas

- Professor Tutor
    - [x] (#58) Gestão das turmas em que é tutor (Tela de gestão de turmas)
    - [x] (#58) Criar turmas em que ele é tutor
    - [x] (#58) Gerir alunos da turma
    - [x] (#50) Moderar forum (pode ocultar questões) de suas turmas

- Relatórios
    - [x] (#59) Análise de progresso no curso por Aluno
    - [x] (#59) Número total de alunos no curso
    - [x] (#59) Listagem dos Alunos do curso, com porcentagem de conclusão do curso.
    - [x] (#59) Porcentagem de conclusão em cada Aula.
    - [x] (#59) Análise de progresso do curso por Aula
    - [x] (#59) Lista de aulas do curso, com a porcentagem de alunos que concluiu cada uma.
    - [x] (#59) Enviar Mensagens para os alunos das suas turmas

- Estudante
    - [x] (#50) Fazer curso
    - [x] (#50) Postar questões no Forum
    - [x] (#50) Responder questões no Forum
    - [x] (#50) Acessar o Material Didático
    - [x] (#50) Receber mensagens dos professores (hoje apenas por email)

**Comment by intrepidocabral** [comment]
@moacirmoda de onde vc pegou isso daqui? 

 (NÃO ACHEI) Número total de usuário que concluíram cada curso
(NÃO ACHEI) Porcentagem dos alunos que concluíram cada curso
(NÃO ACHEI) Número de alunos por curso
(NÃO ACHEI) Estatísticas por turma
(NÃO ACHEI) Mesmas estatísticas do professor tutor, porém com a possibilidade de ver dados de todas as turmas.

**Comment by moacirmoda** [comment]
@robertkapa foi de alguma documentação que encontrei no próprio repo, creio eu. Tentei localizar novamente e não encontrei.
